### ISSUE TITLE
PyPI name for active project?

### ISSUE THREAD

**Issue by MSeal** [bkief/testbook#5]
Hello bkief,

We're developers in the nteract project and coincidentally started a project with the same name as yours several months ago for testing jupyter notebooks: testbook. We looked though your project after discovering that the PyPI name was reserved and wanted to know if A) you'd be willing to let the nteract testbook project take the PyPI name as it's much more developed and will continue to be developed through the nteract org for a while and B) if you'd be interested in working on the nteract version of notebook testing with us since you have been investing efforts in this concept?

Best,
Matt & Rohit

**Comment by bkief** [comment]
@MSeal I am familiar with nteract and I am open helping the project out. I'll reach out over slack.
